spring.config.activate.on-profile: local

redis:
  host: 127.0.0.1
  port: 6379

---
spring.config.activate.on-profile: dev

redis:
  host: 127.0.0.1
  port: 6379

---
spring.config.activate.on-profile: prod

redis:
  host: 127.0.0.1
  port: 6379
