spring:
  application:
    name: api
  profiles:
    active: local
  config:
    import:
      - application-swagger.yml
      - application-client.yml
      - application-redis.yml
      - application-database.yml
server:
  port: 8080
  shutdown: graceful
