spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ssadagame?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssadagame
    password: ssadagame

---
spring.config.activate.on-profile: dev

spring:
  datasource:
    url: jdbc:mysql://database-1.c92uwi206pce.ap-northeast-2.rds.amazonaws.com:3306/ssadagame?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssadagame
    password: ssadagame

---
spring.config.activate.on-profile: prod

spring:
  datasource:
    url: jdbc:mysql://database-1.c92uwi206pce.ap-northeast-2.rds.amazonaws.com:3306/ssadagame?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssadagame
    password: ssadagame
