spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ssadagame?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssadagame
    password: ssadagame

---
spring.config.activate.on-profile: dev

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssadagame?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssadagame
    password: ssadagame

---
spring.config.activate.on-profile: prod

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssadagame?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssadagame
    password: ssadagame
