spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssadagame_batch
    username: root
    password: rnjs02891@
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
