client:
  steam:
    storeUrl: "https://store.steampowered.com"
    apiUrl: "https://api.steampowered.com"
  greenman-gaming:
    serverUrl: "https://sczizsp09z-2.algolianet.com"
    frontUrl: "https://www.greenmangaming.com"
