spring:
  application:
    name: batch
  profiles:
    active: local
  config:
    import:
      - application-database.yml
      - application-redis.yml
      - application-client.yml
server:
  port: 8081
  shutdown: graceful
